### ISSUE TITLE
Luke 13:23 was duplicated in the source text as an extra verse 22

### ISSUE THREAD

**Issue by DavidHaslam** [jonBitgood/Transcription-Efate-Luke#3]
While I was fixing the verse tags in my repository branch, I found this error in the source text.

![screenshot 2017-08-02 14 07 13](https://user-images.githubusercontent.com/16325414/28875046-1138d3e6-778c-11e7-8b0d-5bc514057f28.png)

The text for verse 23 also appears an an extra verse 22.

This issue was resolved in my commit earlier today.

**Comment by jonbitgood** [comment]
Good Catch, I've pulled your commit. It feels kind of unusual to be fixing misprints that go all the way back to the original printing back in 1877.
